"""Actualizando

Revision ID: a7e7cdc82d4d
Revises: c63a4f6b9444
Create Date: 2023-10-22 17:54:27.122747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e7cdc82d4d'
down_revision: Union[str, None] = 'c63a4f6b9444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
