"""Añadida reseña

Revision ID: c63a4f6b9444
Revises: 6879bb19ff67
Create Date: 2023-10-21 20:37:07.671991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63a4f6b9444'
down_revision: Union[str, None] = '6879bb19ff67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_ratings', sa.Column('review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_ratings', 'review')
    # ### end Alembic commands ###
