"""isbn

Revision ID: d7c3e3676de8
Revises: a4f5edfec794
Create Date: 2023-10-27 21:01:29.752357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c3e3676de8'
down_revision: Union[str, None] = 'a4f5edfec794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('isbn', table_name='book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('isbn', 'book', ['isbn'], unique=False)
    # ### end Alembic commands ###
