version: '3.8'

services:
  app:
    build: 
      context: ./front
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api/app:/app/app
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@db:3306/readconnect
      - SECRET_KEY=readconnect
      - ALGORITHM=HS256
      - DATABASE_NAME=readconnect
    restart: always 
      
    depends_on:
      - db 

  db:
    image: mysql:8.0.35-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=readconnect
    ports:
      - 3306:3306
    volumes:
      - readconnect:/var/lib/mysql 

volumes:
  readconnect:
